# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: books_scraper/proto/product_parser.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'books_scraper/proto/product_parser.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(books_scraper/proto/product_parser.proto\x12\rbooks_scraper\"#\n\x13ParseProductRequest\x12\x0c\n\x04html\x18\x01 \x01(\t\"\x16\n\x14ParseProductResponse2i\n\rProductParser\x12X\n\rParseAndStore\x12\".books_scraper.ParseProductRequest\x1a#.books_scraper.ParseProductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_scraper.proto.product_parser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARSEPRODUCTREQUEST']._serialized_start=59
  _globals['_PARSEPRODUCTREQUEST']._serialized_end=94
  _globals['_PARSEPRODUCTRESPONSE']._serialized_start=96
  _globals['_PARSEPRODUCTRESPONSE']._serialized_end=118
  _globals['_PRODUCTPARSER']._serialized_start=120
  _globals['_PRODUCTPARSER']._serialized_end=225
# @@protoc_insertion_point(module_scope)
