# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from books_scraper.proto import product_parser_pb2 as books__scraper_dot_proto_dot_product__parser__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in books_scraper/proto/product_parser_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductParserStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseAndStore = channel.unary_unary(
                '/books_scraper.ProductParser/ParseAndStore',
                request_serializer=books__scraper_dot_proto_dot_product__parser__pb2.ParseProductRequest.SerializeToString,
                response_deserializer=books__scraper_dot_proto_dot_product__parser__pb2.ParseProductResponse.FromString,
                _registered_method=True)


class ProductParserServicer:
    """Missing associated documentation comment in .proto file."""

    def ParseAndStore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductParserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseAndStore': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseAndStore,
                    request_deserializer=books__scraper_dot_proto_dot_product__parser__pb2.ParseProductRequest.FromString,
                    response_serializer=books__scraper_dot_proto_dot_product__parser__pb2.ParseProductResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'books_scraper.ProductParser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('books_scraper.ProductParser', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductParser:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ParseAndStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/books_scraper.ProductParser/ParseAndStore',
            books__scraper_dot_proto_dot_product__parser__pb2.ParseProductRequest.SerializeToString,
            books__scraper_dot_proto_dot_product__parser__pb2.ParseProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
